//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Search.Properties.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act.
        /// </summary>
        internal static string AlarmColAct {
            get {
                return ResourceManager.GetString("AlarmColAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string AlarmColCode {
            get {
                return ResourceManager.GetString("AlarmColCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AlarmColDate {
            get {
                return ResourceManager.GetString("AlarmColDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string AlarmColObject {
            get {
                return ResourceManager.GetString("AlarmColObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string AlarmColText {
            get {
                return ResourceManager.GetString("AlarmColText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AlarmColUser {
            get {
                return ResourceManager.GetString("AlarmColUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string DbErrorCaption {
            get {
                return ResourceManager.GetString("DbErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not be empty.
        /// </summary>
        internal static string errorProvider1msg1 {
            get {
                return ResourceManager.GetString("errorProvider1msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Layout.
        /// </summary>
        internal static string frmPdfTextCab {
            get {
                return ResourceManager.GetString("frmPdfTextCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEU Codes.
        /// </summary>
        internal static string frmPdfTextFeu {
            get {
                return ResourceManager.GetString("frmPdfTextFeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string frmPdfTextLoop {
            get {
                return ResourceManager.GetString("frmPdfTextLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local DB.
        /// </summary>
        internal static string LabelDbLocal {
            get {
                return ResourceManager.GetString("LabelDbLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote DB.
        /// </summary>
        internal static string LabelDbRemote {
            get {
                return ResourceManager.GetString("LabelDbRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string LabelObject {
            get {
                return ResourceManager.GetString("LabelObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string LabelPlace {
            get {
                return ResourceManager.GetString("LabelPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete alarm record?.
        /// </summary>
        internal static string msgDelAlarmText {
            get {
                return ResourceManager.GetString("msgDelAlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        internal static string msgDelAlarmTitle {
            get {
                return ResourceManager.GetString("msgDelAlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to remote database. Do you want to configure remote database path?.
        /// </summary>
        internal static string msgRemoteDbError {
            get {
                return ResourceManager.GetString("msgRemoteDbError", resourceCulture);
            }
        }
    }
}
